# Generated by Django 6.1 on 2026-08-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="region",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="trainer",
            name="sprite_url",
            field=models.URLField(blank=True),
        ),
    ]
