# Generated by Django 6.1 on 2026-08-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0002_trainer_region_trainer_sprite_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownedpokemon",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_pokemons",
                to="trainers.trainer",
            ),
        ),
    ]
