# Generated by Django 6.1 on 2026-08-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0003_alter_ownedpokemon_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownedpokemon",
            name="exp_to_next_level",
            field=models.IntegerField(default=100),
        ),
    ]
