# Generated by Django 6.1 on 2026-09-02 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trainers", "0004_ownedpokemon_exp_to_next_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("potion", "伤药"),
                            ("pokeball", "精灵球"),
                            ("heal", "状态治愈"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.IntegerField(default=0)),
                (
                    "effect_value",
                    models.IntegerField(default=0, help_text="回复量/捕捉率加成等"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="🧪", help_text="emoji 图标", max_length=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.item"
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trainers.trainer",
                    ),
                ),
            ],
            options={
                "unique_together": {("trainer", "item")},
            },
        ),
    ]
