# Generated by Django 6.1 on 2026-08-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("power", models.IntegerField(default=0)),
                ("accuracy", models.IntegerField(default=100)),
                ("pp", models.IntegerField(default=10)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "strong_against",
                    models.ManyToManyField(
                        blank=True, related_name="weak_against", to="pokedex.type"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("bash_hp", models.IntegerField(default=50)),
                ("base_attack", models.IntegerField(default=50)),
                ("base_defense", models.IntegerField(default=50)),
                ("base_speed", models.IntegerField(default=50)),
                ("sprite_url", models.URLField(blank=True)),
                (
                    "evolution_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evolutions",
                        to="pokedex.pokemon",
                    ),
                ),
                (
                    "moves",
                    models.ManyToManyField(
                        blank=True, related_name="learned_by", to="pokedex.move"
                    ),
                ),
                (
                    "type",
                    models.ManyToManyField(related_name="pokemon", to="pokedex.type"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="move",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pokedex.type"
            ),
        ),
    ]
