# Generated by Django 6.1 on 2026-08-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("power", models.IntegerField(default=0)),
                ("accuracy", models.IntegerField(default=100)),
                ("pp", models.IntegerField(default=10)),
                ("priority", models.IntegerField(default=0)),
                ("damage_class", models.IntegerField(default=2)),
                ("generation_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokemon_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("species_id", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
                ("base_experience", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("base_hp", models.IntegerField(default=50)),
                ("base_attack", models.IntegerField(default=50)),
                ("base_defense", models.IntegerField(default=50)),
                ("base_speed", models.IntegerField(default=50)),
                ("sprite_url", models.URLField(blank=True)),
                (
                    "evolution_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evolutions",
                        to="pokedex.pokemon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learn_level", models.IntegerField(default=1)),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pokedex.move"
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokedex.pokemon",
                    ),
                ),
            ],
            options={
                "unique_together": {("pokemon", "move")},
            },
        ),
        migrations.AddField(
            model_name="pokemon",
            name="moves",
            field=models.ManyToManyField(
                related_name="learned_by",
                through="pokedex.PokemonMove",
                to="pokedex.move",
            ),
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "strong_against",
                    models.ManyToManyField(
                        blank=True, related_name="weak_against", to="pokedex.type"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="type",
            field=models.ManyToManyField(related_name="pokemon", to="pokedex.type"),
        ),
        migrations.AddField(
            model_name="move",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pokedex.type"
            ),
        ),
    ]
