# Generated by Django 6.1 on 2026-08-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="bash_hp",
            new_name="base_hp",
        ),
    ]
