# Generated by Django 6.1 on 2026-09-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="immune",
            field=models.ManyToManyField(
                blank=True, related_name="immune_by", to="pokedex.type"
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="resist",
            field=models.ManyToManyField(
                blank=True, related_name="resisted_by", to="pokedex.type"
            ),
        ),
    ]
